Repository pagopa/pagopa-platform-integration-test, pull requests merged in 2025-04, with the labels that each got.

#22 feat: [PQ-296] Add eBollo step implementation
  README.md
  config.yaml
  config/.secrets_template.yaml
  requirements.txt
  src/bdd/ebollo/environment.py
  src/bdd/ebollo/features/citizen_buys_ebollo.feature
  src/bdd/ebollo/steps/user_steps.py
  src/conf/configuration.py
  src/utility/ebollo/api.py
  src/utility/ebollo/ui.py
  src/utility/ebollo/utils.py
Labels: size/small

#25 feat: PQ-367 landing page improvement
  .github/workflows/deploy-test-report.yml
  .github/workflows/fdr-tests.yml
  .github/workflows/main-dispatch-tests.yml
  .github/workflows/run_behave_tests.yml
  .github/workflows/wisp-tests.yml
  landing-page/index.html
Labels: enhancement, size/large

#26 feat: PQ-367 test management improvements
  .github/workflows/deploy-test-report.yml
  .github/workflows/main-dispatch-tests.yml
  landing-page/index.html
  templates/history-index-template.html
Labels: enhancement, size/small

#29 feat: PQ-367 generalize deploy report
  .github/scripts/notify_slack.py
  .github/workflows/deploy-test-report.yml
  .github/workflows/main-dispatch-tests.yml
  landing-page/index.html
Labels: enhancement

#30 feat: PQ-367-update scripts checkout
  .github/workflows/deploy-test-report.yml
Labels: enhancement, size/small

#31 feat: PQ-367 add slack notification
  .github/scripts/notify_slack.py
  .github/workflows/deploy-test-report.yml
  templates/history-index-template.html
Labels: enhancement
